on click and on hover actions for recordm images
cob/customize.keywords.image pull request #1
Opened 2023-01-27 16:29 UTC by angelo-234

2023-01-27 16:41 UTC, adagios commented on recordm/customUI/js/cob/_image.js
> +        let show = 1
1 e 0 em vez de true e false? não gosto

2023-01-27 16:45 UTC, adagios commented on recordm/customUI/js/cob/_image.js
> +        function onImageClick(){
isto tudo pode ser trocado por algo tipo:
```
const replaceArgMatcher = new RegExp(`\\(\\[.*replace:${show ? 'false' : 'true' }.*\\]\\)`);
....
show = !show
```
ou parecido

2023-01-27 16:46 UTC, adagios commented on recordm/customUI/js/cob/_image.js
> +            "<span "+ widthCalc +">Click to toggle image details</span>" +
se vão acrescentar texto, como é que se traduz?

2023-01-27 17:03 UTC, adagios commented on recordm/customUI/js/cob/_image.js
> +          '<div class="tooltip-hover"'+ widthCalc +'>' +
acho que fica a faltar um espaço a separar o class do style

2023-01-27 17:06 UTC, adagios commented on recordm/customUI/js/cob/_image.js
> +          const replaceFlag = args && args.match(replaceArgMatcher) && args.match(replaceArgMatcher).length == 1
não percebo exactamente o que faz esta linha
o que é que vem no args?

2023-01-27 18:13 UTC, angelo-234 commented on recordm/customUI/js/cob/_image.js
> +          const replaceFlag = args && args.match(replaceArgMatcher) && args.match(replaceArgMatcher).length == 1
Tens razão, estas linhas eram desnecessárias. Já fiz um novo commit

2023-01-27 18:45 UTC, mimes70 commented
Falta tb aumentar a minor version no `customize.js`.

2023-01-27 18:51 UTC, mimes70 requested changes

2023-01-27 18:51 UTC, mimes70 commented on recordm/customUI/js/cob/_image.js
> +          '<div class="tooltip-hover"'+ widthCalc +'>' +
acho que o nome da classe deve ser mais específico. Algo tipo `dollarImageDiv`.

2023-01-27 18:51 UTC, mimes70 commented on recordm/customUI/js/cob/_image.js
> +        $image[0].onclick = onImageClick2
Não percebo porque chamar `onImageClick2` e não `onImageClick`

2023-01-27 18:51 UTC, mimes70 commented on recordm/customUI/js/cob/_image.js
> +          '<div class="tooltip-hover"'+ widthCalc +'>' +
Continua a faltar um espaço antes do style (apesar de talvez funcionar nalguns browsers menos estritos)

2023-01-31 11:18 UTC, adagios commented on recordm/customUI/js/cob/_image.js
> +            "<span "+ widthCalc +">Click to toggle image details</span>" +
`core.getLanguage()`

2023-02-02 15:19 UTC, merged